In [2]:
import torch 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import os

In [5]:
path = os.path.join(os.path.expanduser("~"), "Downloads", "checkpoint.pth")
checkpoint = torch.load(path, map_location=torch.device("cpu"), weights_only=False)

In [7]:
checkpoint["train_loss"]

[1.130995596034935,
 1.1061943404917556,
 1.1002654317694454,
 1.0983161290910226,
 1.097386085057878,
 1.0972973584016905,
 1.097195863564915]

In [8]:
checkpoint["val_loss"]

[1.1381471512165475,
 1.1150221317372424,
 1.1142160131576213,
 1.1148578562635056,
 1.114593100040517,
 1.114706648156998,
 1.1139864008477394]

In [10]:
val_metrics = checkpoint["val_metrics"]
accuracies = [metrics["accuracy"] for metrics in val_metrics]

In [11]:
accuracies

[array([0.25531915, 0.77958775, 0.73769945, 0.7849069 , 0.9255319 ],
       dtype=float32),
 array([0.39361703, 0.12400266, 0.61336434, 0.7849069 , 0.9255319 ],
       dtype=float32),
 array([0.24202128, 0.87599736, 0.34707448, 0.7849069 , 0.9255319 ],
       dtype=float32),
 array([0.75797874, 0.87599736, 0.73537236, 0.21509309, 0.9255319 ],
       dtype=float32),
 array([0.75797874, 0.87599736, 0.26230052, 0.21509309, 0.9255319 ],
       dtype=float32),
 array([0.24202128, 0.12400266, 0.73769945, 0.7849069 , 0.9255319 ],
       dtype=float32),
 array([0.24202128, 0.12400266, 0.73769945, 0.21509309, 0.9255319 ],
       dtype=float32)]